AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 180

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 1500
  
Metrics/CyclomaticComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 15

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Enabled: false
  
Metrics/PerceivedComplexity:
  Max: 20

Metrics/BlockLength:
  Max: 70

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
